spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: bobirival
    password: password@147
    url: jdbc:postgresql://localhost:5432/demo-notification-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect